# Generated by Django 3.1.7 on 2021-04-09 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_code', models.PositiveIntegerField(help_text='Unique code for each location. For example Brussels-Belgium:5602, East Flanders-Belgium:5603')),
                ('country_code', models.PositiveIntegerField(help_text='Unique code for a country. For example Belgium:56')),
                ('iso2', models.CharField(blank=True, max_length=10)),
                ('iso3', models.CharField(blank=True, max_length=10)),
                ('fibs', models.CharField(blank=True, max_length=10)),
                ('province_state', models.CharField(blank=True, max_length=255)),
                ('country_region', models.CharField(blank=True, max_length=255)),
                ('location_name', models.CharField(blank=True, help_text='For example Antwerp, Belgium', max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('country_population', models.PositiveIntegerField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('longitute', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.JSONField(blank=True, default=dict, null=True)),
                ('deaths', models.JSONField(blank=True, default=dict, null=True)),
                ('recovered', models.JSONField(blank=True, default=dict, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timelines', to='tracker.location')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('confirmed', models.PositiveIntegerField()),
                ('deaths', models.PositiveIntegerField()),
                ('recovered', models.PositiveIntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='tracker.location')),
            ],
        ),
    ]
