# Generated by Django 3.1.7 on 2021-03-07 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_id', models.PositiveIntegerField()),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('country_code', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=255)),
                ('country_population', models.PositiveIntegerField()),
                ('province', models.CharField(blank=True, max_length=255, null=True)),
                ('county', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.JSONField(blank=True, default=dict, null=True)),
                ('deaths', models.JSONField(blank=True, default=dict, null=True)),
                ('recovered', models.JSONField(blank=True, default=dict, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.location')),
            ],
        ),
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('longitute', models.DecimalField(decimal_places=16, max_digits=22)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tracker.location')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('confirmed', models.PositiveIntegerField()),
                ('deaths', models.PositiveIntegerField()),
                ('recovered', models.PositiveIntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.location')),
            ],
        ),
    ]
