# Generated by Django 3.1.7 on 2021-04-10 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('vaccines', models.CharField(blank=True, max_length=256)),
                ('total_vaccinations', models.PositiveIntegerField(blank=True, help_text='Total number of doses administered', null=True)),
                ('total_vaccinations_per_hundred', models.DecimalField(blank=True, decimal_places=2, help_text='total_vaccinations per 100 people', max_digits=2, null=True)),
                ('people_vaccinated', models.PositiveIntegerField(blank=True, help_text='total number of people who received at least one vaccine dose', null=True)),
                ('people_vaccinated_per_hundred', models.DecimalField(blank=True, decimal_places=2, help_text='people_vaccinated per 100 people', max_digits=2, null=True)),
                ('people_fully_vaccinated', models.PositiveIntegerField(blank=True, help_text='total number of people who received all doses prescribed', null=True)),
                ('people_fully_vaccinated_per_hundred', models.DecimalField(blank=True, decimal_places=2, help_text='people_fully_vaccinated per 100 people', max_digits=2, null=True)),
                ('daily_vaccinations_raw', models.PositiveIntegerField(blank=True, help_text='daily change in the total number of doses administered', null=True)),
                ('daily_vaccinations', models.PositiveIntegerField(blank=True, help_text='new doses administered per day', null=True)),
                ('daily_vaccinations_per_million', models.DecimalField(blank=True, decimal_places=2, help_text='daily_vaccinations per 1,000,000 people in the total population of the country.', max_digits=2, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='tracker.location')),
            ],
        ),
    ]
