# Generated by Django 3.1.7 on 2021-04-09 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='country',
        ),
        migrations.RemoveField(
            model_name='location',
            name='country_id',
        ),
        migrations.RemoveField(
            model_name='location',
            name='county',
        ),
        migrations.RemoveField(
            model_name='location',
            name='province',
        ),
        migrations.AddField(
            model_name='location',
            name='country_region',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='location',
            name='fibs',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='location',
            name='iso2',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='location',
            name='iso3',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='location_code',
            field=models.PositiveIntegerField(default=1, help_text='Unique code for each location. For example Brussels-Belgium:5602, East Flanders-Belgium:5603'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='location_name',
            field=models.CharField(blank=True, help_text='For example Antwerp, Belgium', max_length=255),
        ),
        migrations.AddField(
            model_name='location',
            name='longitute',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='province_state',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='case',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='tracker.location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='country_code',
            field=models.PositiveIntegerField(help_text='Unique code for a country. For example Belgium:56'),
        ),
        migrations.AlterField(
            model_name='location',
            name='country_population',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timelines', to='tracker.location'),
        ),
    ]
