# Generated by Django 3.1.7 on 2021-04-10 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_vaccination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccination',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination', to='tracker.location'),
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccines', models.CharField(blank=True, help_text='Vaccines', max_length=256)),
                ('last_observation_date', models.DateField()),
                ('source_name', models.CharField(blank=True, max_length=256)),
                ('source_website', models.URLField(blank=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccines', to='tracker.location')),
            ],
        ),
    ]
