# Generated by Django 3.1.7 on 2021-04-09 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20210409_1345'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coordinates',
        ),
    ]
