# Generated by Django 3.1.7 on 2021-04-10 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20210410_1643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['-date', 'id']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='timeline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='vaccination',
            options={'ordering': ['-date', 'id']},
        ),
        migrations.AlterModelOptions(
            name='vaccine',
            options={'ordering': ['id']},
        ),
    ]
