# Generated by Django 3.1.7 on 2021-10-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20211017_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='country_population',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
